#!/usr/bin/env python3
"""Rebuild ~/.claude/repo-context/INDEX.md from the frontmatter of every
context file in that folder.

The index is the cheap "is this repo even relevant?" lookup: one line per
repo (type, summary, related repos) so a session can scan it without opening
any full context file. Because it reads the folder fresh every time, the
index stays correct no matter which repos a given /repo-context run touched
(single-repo refresh, skip-existing, or full rebuild).

No third-party deps on purpose — this has to run on a freshly-set-up machine
before anything like pyyaml is installed. The frontmatter format is the small
controlled subset /repo-context writes, so a hand parser is enough.
"""

import os
import sys

CONTEXT_DIR = os.path.expanduser("~/.claude/repo-context")
INDEX_NAME = "INDEX.md"
# Order groups so the two sides are always visually separated, unknown last.
GROUP_ORDER = ["work", "personal", "unknown"]


def parse_frontmatter(path):
    """Return the frontmatter dict for a context file, or {} if it has none."""
    with open(path, encoding="utf-8") as handle:
        lines = handle.read().splitlines()
    if not lines or lines[0].strip() != "---":
        return {}
    fields = {}
    current_key = None
    for line in lines[1:]:
        if line.strip() == "---":
            break
        if ":" in line and not line.startswith((" ", "\t")):
            key, _, value = line.partition(":")
            current_key = key.strip()
            fields[current_key] = value.strip()
        elif current_key is not None and line.strip():
            # Folded continuation of the previous value (e.g. a wrapped summary).
            fields[current_key] = (fields[current_key] + " " + line.strip()).strip()
    return fields


def parse_list(raw):
    """Turn a `[a, b]` (or bare/empty) frontmatter value into a list of names."""
    if not raw:
        return []
    raw = raw.strip()
    if raw in ("[]", "~", "none", "[ ]"):
        return []
    raw = raw.strip("[]")
    return [item.strip().strip("'\"") for item in raw.split(",") if item.strip()]


def related_suffix(fields):
    """Render the related-repos tail shown after each summary, or '' if none."""
    parts = []
    depends = parse_list(fields.get("depends_on", ""))
    used_by = parse_list(fields.get("used_by", ""))
    if depends:
        parts.append("depends on: " + ", ".join(depends))
    if used_by:
        parts.append("used by: " + ", ".join(used_by))
    return f" _({' · '.join(parts)})_" if parts else ""


def main():
    if not os.path.isdir(CONTEXT_DIR):
        print(f"No context dir at {CONTEXT_DIR}; nothing to index.", file=sys.stderr)
        return 1

    groups = {name: [] for name in GROUP_ORDER}
    for filename in sorted(os.listdir(CONTEXT_DIR)):
        if not filename.endswith(".md") or filename == INDEX_NAME:
            continue
        repo = filename[:-3]
        fields = parse_frontmatter(os.path.join(CONTEXT_DIR, filename))
        repo_type = fields.get("type", "unknown").strip().lower()
        if repo_type not in groups:
            repo_type = "unknown"
        summary = fields.get("summary", "").strip()
        if not summary:
            summary = "_(no frontmatter — run `/repo-context " + repo + "` to refresh)_"
        # One scannable line per repo on purpose: this is a lookup table, not
        # prose, so a row may run past the usual 140-char markdown width. The
        # per-file `summary` field stays under 140; only this rendered row,
        # which appends the repo name and related repos, can exceed it.
        groups[repo_type].append(f"- **{repo}** — {summary}{related_suffix(fields)}")

    out_lines = [
        "# Repo Context Index",
        "",
        "> Auto-generated by `/repo-context`. One line per repo: type, summary, related repos.",
        "> Read this first to find which repos a task touches, then open only the relevant",
        "> `~/.claude/repo-context/<name>.md` files. Do not hand-edit — it is regenerated.",
        "",
    ]
    total = 0
    for name in GROUP_ORDER:
        entries = groups[name]
        if not entries:
            continue
        total += len(entries)
        out_lines.append(f"## {name}")
        out_lines.append("")
        out_lines.extend(entries)
        out_lines.append("")

    with open(os.path.join(CONTEXT_DIR, INDEX_NAME), "w", encoding="utf-8") as handle:
        handle.write("\n".join(out_lines).rstrip() + "\n")

    print(f"Wrote {INDEX_NAME} with {total} repo(s).")
    return 0


if __name__ == "__main__":
    sys.exit(main())
