#!/usr/bin/env sh

# General Settings
yabai -m config mouse_follows_focus      off
yabai -m config focus_follows_mouse      off
yabai -m config window_placement         center
yabai -m config window_topmost           off
yabai -m config window_shadow            on
yabai -m config window_opacity           off
yabai -m config window_border            on
yabai -m config active_window_border_topmost on
yabai -m config window_border_width      3
yabai -m config window_border_radius     5
yabai -m config active_window_border_color   0xffff3050
yabai -m config normal_window_border_color   0xFFCCCCCC #0xffaaaaaa
yabai -m config insert_feedback_color    0xFFFFFFFF # 0xffd75f5
#yabai -m config split_ratio                  0.50

# Spaces
yabai -m config layout                       bsp
yabai -m config top_padding                  0
yabai -m config bottom_padding               0
yabai -m config left_padding                 0
yabai -m config right_padding                0
yabai -m config window_gap                   0
yabai -m config auto_balance                 off
#yabai -m config mouse_action1                move
yabai -m config space_padding                0

# resize windows if resized with mouse
yabai -m config mouse_action2                resize
yabai -m config mouse_drop_action            swap

## Setup all windows
# Space 1
#yabai -m space --create
#yabai -m space --focus 1
#yabai -m window --grid 2:2:1:1:1:2

# apps to not manage (ignore)
yabai -m rule --add app="System Preferences" manage=off
yabai -m rule --add app="Messages" manage=off
yabai -m rule --add app="Activity Monitor" manage=off
yabai -m rule --add app="Finder" manage=off
yabai -m rule --add app="Postman" manage=off
yabai -m rule --add app="Spotify" manage=off
yabai -m rule --add app="Calendar" manage=off
yabai -m rule --add app="Figma" manage=off
yabai -m rule --add app="Insomnia" manage=off
yabai -m rule --add app="Teams" manage=off
yabai -m rule --add app="Discord" manage=off
yabai -m rule --add app="Messages" manage=off

# Space 2
#yabai -m space --create
#yabai -m space --focus 2
#yabai -m window --grid 2:2:1:1:1:2
#open -a "iTerm"
#open -a "Mail"

